version: "3.3"

services:
  # vote:
  #   build: ./vote
  #   command: python app.py
  #   volumes:
  #    - ./vote:/app
  #   ports:
  #     - "5000:80"

  backend:
    build: ./backend
    command: sh -c "npm install && npm install -g nodemon && nodemon"
    volumes:
      - back:/app
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    command: sh -c "npm install && npm install --save-dev nodemon && nodemon /app"
    volumes:
      - front:/app
    ports:
      - "3000:3000"
  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
  front:
    driver: local
    driver_opts:
      type: none
      device: $PWD/frontend
      o: bind
  back:
    driver: local
    driver_opts:
      type: none
      device: $PWD/backend
      o: bind
